/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "platform_types.h"
/* RCC */
#define RCC_BASE 		0x40021000
#define RCC_APB2ENR		*((vuint32_t*)(RCC_BASE+0X18))

/* GPIO */
#define GPIO_PA_BASE 	0x40010800
#define GPIOA_CRH		*((vuint32_t*)(GPIO_PA_BASE+0X04))
#define GPIOA_ODR		*((vuint32_t*)(GPIO_PA_BASE+0X0C))
#define GPIOA_CRL		*((vuint32_t*)(GPIO_PA_BASE+0X00))

#define AFIO_BASE		0x40010000
#define AFIO_EXTICR1	*((vuint32_t*)(AFIO_BASE+0x08))

#define EXTI_BASE		0x40010400
#define EXTI_IMR		*((vuint32_t*)(EXTI_BASE+0X00))
#define EXTI_RTSR		*((vuint32_t*)(EXTI_BASE+0X08))
#define EXTI_PR			*((vuint32_t*)(EXTI_BASE+0X14))

#define NVIC_ISER0		*((vuint32_t*)(0xE000E100))

void cloack_init()
{
	RCC_APB2ENR |=	1<<2 ;
}

void GPIO_init()
{
	//GPIOA_Pin_0
	GPIOA_CRL	|=	0b01<<2 ;
	//GPIOA_Pin_13
	GPIOA_CRH	&= 	0xff0fffff;
	GPIOA_CRH	|= 	0x00200000;
}

int main(void)
{
	cloack_init();
	GPIO_init();

	//	Bits 15:0 EXTIx[3:0]: EXTI x configuration (x= 0 to 3)
	//	These bits are written by software to select the source input for EXTIx external interrupt.
	//	Refer to Section 10.2.5: External interrupt/event line mapping
	//	0000: PA[x] pin
	//	0001: PB[x] pin
	//	0010: PC[x] pin
	//	0011: PD[x] pin
	//	0100: PE[x] pin
	//	0101: PF[x] pin
	//	0110: PG[x] pin
	AFIO_EXTICR1|=	0b0000<<0;

	//	Bits 19:0 TRx: Rising trigger event configuration bit of line x
	//	0: Rising trigger disabled (for Event and Interrupt) for input line
	//	1: Rising trigger enabled (for Event and Interrupt) for input line.
	//	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.
	EXTI_RTSR	|=	1<<0 ;

	//	Bits 19:0 MRx: Interrupt Mask on line x
	//	0: Interrupt request from Line x is masked
	//	1: Interrupt request from Line x is not masked
	//	Note: Bit 19 is used in connectivity line devices only and is reserved otherwise.
	EXTI_IMR 	|=	1<<0;

	NVIC_ISER0 	|=	1<<6 ;


	while(1);
}

void EXTI0_IRQHandler(void)
{
	GPIOA_ODR	^=	1<<13;

	EXTI_PR		|=	1<<0;
}
