/**
 ******************************************************************************
 * @file           : main.c
 * @author         : Auto-generated by STM32CubeIDE
 * @brief          : Main program body
 ******************************************************************************
 * @attention
 *
 * <h2><center>&copy; Copyright (c) 2023 STMicroelectronics.
 * All rights reserved.</center></h2>
 *
 * This software component is licensed by ST under BSD 3-Clause license,
 * the "License"; You may not use this file except in compliance with the
 * License. You may obtain a copy of the License at:
 *                        opensource.org/licenses/BSD-3-Clause
 *
 ******************************************************************************
 */

#if !defined(__SOFT_FP__) && defined(__ARM_FP)
  #warning "FPU is not initialized, but the project is compiling for an FPU. Please initialize the FPU before use."
#endif

#include "Stm32F103x6.h"
#include "Stm32F103C6_GPIO_Driver.h"
#include "Stm32F103C6_EXTI_Driver.h"
#include "LCD.h"
#include "KEYPAD.h"

void clock_init();
void GPIO_init();

void wait(uint32_t time);
void EXTI9_callback(void);

uint8_t EXTI_flag = 0;
int main(void)
{
	clock_init();
	LCD_init();
	LCD_clear_screen();

	EXTI__PIN_Config_t EXTI_CFG;
	EXTI_CFG.EXTI_PIN = EXTIPB9 ;
	EXTI_CFG.Trigger_Case = EXTI_Trigger_RISING ;
	EXTI_CFG.P_IRQ_CallBack = EXTI9_callback ;
	EXTI_CFG.IRQ_EN =EXTI_IRQ_ENABLE ;

	EXTI_GPIO_Init(&EXTI_CFG);
	EXTI_flag=1;
	while(1)
	{
		if(EXTI_flag)
		{
			LCD_clear_screen() ;
			EXTI_flag = 0;
		}
	}

}

void clock_init()
{
	RCC_GPIOA_CLK_EN() 	;
	RCC_GPIOB_CLK_EN() 	;
	RCC_AFIO_CLK_EN()	;

}


void wait(uint32_t time)
{
	uint32_t i,j;
	for(i=0;i<time;i++)
		for(j=0;j<255;j++);
}

void EXTI9_callback(void)
{
	EXTI_flag = 1;
	LCD_WRITE_STRING("IRQ EXTI9 is happened _|-  ") ;
	wait(1000);

}

